### PR TITLE
doc: update development process doc with new merge rule

### PR DESCRIPTION
**Pull request by CodeLeom**
**Description**:

This PR modifies the development process documentation on the new improved PR merging rule.

**Related issue(s)**: https://github.com/hashgraph/hedera-sdk-tck/issues/235

### CODE REVIEW

**Comment by samswag** [comment]
@CodeLeom it seems you are missing DCO

Here is how to fix that:

Commit your changes: Here, it is needed to add sign-off information to the commit to accept the "Developer Certificate of Origin" (https://developercertificate.org/).
More details can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md)

**Comment by CodeLeom** [comment]
@samswag thanks for for heads up. I have fixed that, DCO now passes

**Review by rwalworth — APPROVED** [review]
LGTM thanks for your contribution!

**Review by ivaylogarnev-limechain — APPROVED** [review]
LGTM! Thank you :))

**Comment by rwalworth** [comment]
> @samswag thanks for the heads up. I have fixed that, DCO now passes

@CodeLeom it looks like not all of your commits are signed, that is required in order to merge.

**Comment by CodeLeom** [comment]
@rwalworth I was looking for how to sign the previous commit that were unsigned, how do I do that?

**Comment by rwalworth** [comment]
> @rwalworth I was looking for how to sign the previous commit that were unsigned, how do I do that?

I believe you have to rebase and amend your commits. These page seems to have the instructions you're looking for: https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits

**Comment by jsync-swirlds** [comment]
> > @rwalworth I was looking for how to sign the previous commit that were unsigned, how do I do that?
> 
> I believe you have to rebase and amend your commits. These page seems to have the instructions you're looking for: https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits

That's just for signoff, although any amend will _also_ gpg sign the commit, particularly if the local client is setup to do so.

Generally, if you perform an interactive rebase of the 4 commits (i.e. `git rebase -i HEAD~4`) and select `reword` for each (or `squash` for all but the first, if you prefer to collapse all 4 commits into one), you'll be able to add the `signoff` line to each commit and the result will be gpg signed as well.

**Pull request closed without merging**
