### PR TITLE
fix: remove the references to node type in setup test file and custom…

### LINKED ISSUE #236: Remove references to node type
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to [Hedera](https://hedera.com) or any open source project in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'good first issue'**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Ahashgraph+archived%3Afalse+label%3A%22good+first+issue%22+) is to help you make your first contribution to Hedera.

## 👾 Description of the issue

The function `getNodeType()` in `setup_Tests.js` and `NODE_TYPE` in the `.env` files are remnants of an old implementation that is no longer used. These can be removed.

### Proposed Solution:

Remove the `getNodeType()` function from `setup_Tests.js` and the `NODE_TYPE` variable in the `.env.custom_node` and `.env.testnet` environment variable files. To verify functionality, follow the directions in the [README](https://github.com/hashgraph/hedera-sdk-tck/blob/main/README.md) to run an SDK server, and [hedera-local-node](https://github.com/hashgraph/hedera-local-node) if you choose to test locally, then run `npm run test` to run all tests. All tests should pass and no errors should be observed.

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. More information and concrete samples for shell commands for each step can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md) file.
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button).
- [ ] **Check out the forked repository**
- [ ] **Create a feature branch** for the issue. We do not have a hard naming definition for branches but it is best practice to prefix the branch name with the issue id.
- [ ] **Solve the issue** in your branch.
- [ ] **Commit your changes:** Here, it is needed to add `sign-off` information to the commit to accept the "Developer Certificate of Origin" (https://developercertificate.org). More details can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md)
- [ ] **Start a Pull Request (PR)**: We have a pattern for naming pull requests that a GitHub Action checks. We use that pattern to support the creation of automatic release notes.
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error do not hesitate to add a comment to the PR and ask the Hedera developer community for support.
- [ ] **Wait for reviews:** Members of the Hedera developer community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will start a discussion with you and describe the next steps for solving the problem.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of the Hedera community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

## 🤔 Additional Information

If you have any questions, just ask us directly in this issue by adding a comment. You can join our community chat at [Discord](https://hedera.com/discord). A general manual about open-source contributions can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

### PR DESCRIPTION
**Pull request by CodeLeom**
… env. Closes #236

**Description**:
this PR removes the reference to node type in the `setup_Tests.js` file and the custom env files.

**Related issue(s)**:

Fixes #236

### CODE REVIEW

**Comment by rwalworth** [comment]
Did you run the TCK against an SDK server to verify this didn't break anything?

**Comment by CodeLeom** [comment]
@rwalworth it was the test file I ran. Let me run it against an SDK server

**Comment by CodeLeom** [comment]
@rwalworth I tried to run the hedera-sdk-js, I encountered an error of `exit status 127` while running `task install` or how do I test against an SDK server?

**Comment by rwalworth** [comment]
> @rwalworth I tried to run the hedera-sdk-js, I encountered an error of `exit status 127` while running `task install` or how do I test against an SDK server?

@ivaylogarnev-limechain?

**Comment by CodeLeom** [comment]
@ivaylogarnev-limechain yes I have both installed. Now, the error I am facing is no `task file` found

image

**Comment by rwalworth** [comment]
> @ivaylogarnev-limechain yes I have both installed. Now, the error I am facing is no `task file` found

I believe he was referring to running the `hedera-sdk-js` server, not `hedera-sdk-tck`

**Comment by ivaylogarnev-limechain** [comment]
> > @ivaylogarnev-limechain yes I have both installed. Now, the error I am facing is no `task file` found
> 
> I believe he was referring to running the `hedera-sdk-js` server, not `hedera-sdk-tck`


Yep, I will sum up the steps here to run the tests from TCK to JS SDK Server.

1. **Clone and Install the TCK Repository**:Start by cloning the [TCK repository](https://github.com/hashgraph/hedera-sdk-tck) and following the instructions provided in the README file. (Assuming you've already done this step.)
2. **Clone and Install the SDK Repository**: Next, clone the [SDK repository](https://github.com/hashgraph/hedera-sdk-js) and read through the README to ensure proper setup.
3. **Set Up the TCK Server (_within SDK repo_)**: Once you’ve successfully set up the SDK repository, navigate to the **/tck** directory. Install the necessary npm packages by running **npm install**, then start the server with **npm run start**. For easier testing, configure the .env file to use the testnet; otherwise, you’ll need to run a local node for local testing.
4. **Run the Tests**: Finally, execute the tests by running **npm run test** from the root directory of the TCK.

**Comment by CodeLeom** [comment]
@ivaylogarnev-limechain I followed this steps but the SDK is not running. I guess I missing something 😔

**Comment by ivaylogarnev-limechain** [comment]
> @ivaylogarnev-limechain I followed this steps but the SDK is not running. I guess I missing something 😔

Thanks for following the steps! Let’s troubleshoot this together. Could you please try reproducing the issue and let me know exactly what you’re doing? Specifically:

1. At what step does the SDK stop working or fail to run?
2. Are there any error messages appearing in the console, or does it seem to run without any output?
3. What environment (OS, Node version, etc.) are you using?
4. If you’ve made any changes to the .env file or configuration, please share those as well.


Or even you can describe the things you are doing, step by step.

**Comment by ivaylogarnev-limechain** [comment]
@CodeLeom

**Comment by CodeLeom** [comment]
@ivaylogarnev-limechain thank you for the follow up, I will revert today

**Comment by CodeLeom** [comment]
> Clone and Install the TCK Repository: Start by cloning the [TCK repository](https://github.com/hashgraph/hedera-sdk-tck) and following the instructions provided in the README file. (Assuming you've already done this step.)
> Clone and Install the SDK Repository: Next, clone the [SDK repository](https://github.com/hashgraph/hedera-sdk-js) and read through the README to ensure proper setup.
> Set Up the TCK Server (within SDK repo): Once you’ve successfully set up the SDK repository, navigate to the /tck directory. Install the necessary npm packages by running npm install, then start the server with npm run start. For easier testing, configure the .env file to use the testnet; otherwise, you’ll need to run a local node for local testing.
> Run the Tests: Finally, execute the tests by running npm run test from the root directory of the TCK.

@ivaylogarnev-limechain I followed all the steps above till I got to step three, navigating to the TCK folder in the `hedera-sdk-js` file to run `npm run start` but I encountered an error.
Screenshot 2024-10-17 at 09 22 38


I currently Mac OS, node v20.10.0, npm v10.9.0

in my `hedera-sdk-js` env file, I am using the `ed25519` account ID and DER Encoded Private Key. While in the `hedera-sdk-tck` I am using the `ecdsa` account ID and DER Encoded Private Key

**Comment by ivaylogarnev-limechain** [comment]
> > Clone and Install the TCK Repository: Start by cloning the [TCK repository](https://github.com/hashgraph/hedera-sdk-tck) and following the instructions provided in the README file. (Assuming you've already done this step.)
> > Clone and Install the SDK Repository: Next, clone the [SDK repository](https://github.com/hashgraph/hedera-sdk-js) and read through the README to ensure proper setup.
> > Set Up the TCK Server (within SDK repo): Once you’ve successfully set up the SDK repository, navigate to the /tck directory. Install the necessary npm packages by running npm install, then start the server with npm run start. For easier testing, configure the .env file to use the testnet; otherwise, you’ll need to run a local node for local testing.
> > Run the Tests: Finally, execute the tests by running npm run test from the root directory of the TCK.
> 
> @ivaylogarnev-limechain I followed all the steps above till I got to step three, navigating to the TCK folder in the `hedera-sdk-js` file to run `npm run start` but I encountered an error. Screenshot 2024-10-17 at 09 22 38
> 
> I currently use Mac OS, node v20.10.0, npm v10.9.0
> 
> in my `hedera-sdk-js` env file, I am using the `ed25519` account ID and DER Encoded Private Key. While in the `hedera-sdk-tck` I am using the `ecdsa` account ID and DER Encoded Private Key

1. Could you double-check to ensure that you are indeed inside the **tck** directory before running the command?
2. Have the necessary npm packages been installed? If not, I would recommend running **npm install** within the tck directory and then attempting to start the server again

**Comment by CodeLeom** [comment]
yes, I am in the tck directory, and the necessary packages are installed.

@ivaylogarnev-limechain

**Comment by CodeLeom** [comment]
oh ok, I will do so and get back with the response

**Comment by CodeLeom** [comment]
@ivaylogarnev-limechain finally, I was able to set up the SDK server. I also run the server, then run a test against the SDK, one test is failing, see attached image.

@rwalworth, I can now answer your question `Did you run the TCK against an SDK server to verify this didn't break anything?`. Yes, I did not break anything. 


Let me enter the town to buy myself a bottle of coke 😂 .

Thank you @ivaylogarnev-limechain for not forsaking me.

image

**Review by ivaylogarnev-limechain — APPROVED** [review]
LGTM! Thanks for your efforts.

**Review by rwalworth — APPROVED** [review]
LGTM thanks!

**Pull request merged**
